apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - xrd.yaml
  - composition.yaml
  - environment-configs.yaml
  # Note: Don't include examples here - they should be applied separately