# Example: Deploy WhoareApp for local development
apiVersion: demo.openportal.dev/v1alpha1
kind: WhoareApp
metadata:
  name: myapp-local
  namespace: default
spec:
  name: myapp  # Creates myapp.localhost
  replicas: 1
  environment: local