# Example: Deploy WhoareApp for production
apiVersion: demo.openportal.dev/v1alpha1
kind: WhoareApp
metadata:
  name: demo-prod
  namespace: default
spec:
  name: demo  # Creates demo.openportal.dev
  replicas: 3
  environment: production