# Composition: WhoAmIApp Implementation
# Purpose: Implements the WhoAmIApp using provider-kubernetes with environment detection
# Restaurant Analogy: The "recipe" - how to prepare what was ordered
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: whoamiapp-direct
  labels:
    mode: direct
    description: direct-deployment
spec:
  compositeTypeRef:
    apiVersion: openportal.dev/v1alpha1
    kind: WhoAmIApp
  
  mode: Pipeline
  pipeline:
  
  # Step 1: Load environment configuration
  - step: load-environment
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: dns-config  # Global DNS config with zone
  
  # Step 2: Generate resources using go-templating with environment data
  - step: deploy-app
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $replicas := .observed.composite.resource.spec.replicas | default 1 }}
          {{- $image := .observed.composite.resource.spec.image | default "traefik/whoami:v1.10.1" }}
          {{- $xrName := .observed.composite.resource.metadata.name }}
          {{- $xrNamespace := .observed.composite.resource.metadata.namespace }}
          {{- $appName := .observed.composite.resource.spec.name | default "whoami" }}
          
          {{/* Determine domain from dns-config or default to localhost */}}
          {{- $domain := printf "%s.localhost" $appName }}
          {{- $zone := index .context "apiextensions.crossplane.io/environment" "zone" }}
          {{- if $zone }}
            {{- $domain = printf "%s.%s" $appName $zone }}
          {{- end }}
          
          ---
          # Deployment
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $xrName }}-deployment
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $xrName }}-deployment
              crossplane.io/external-name: {{ $xrName }}-deployment
          spec:
            forProvider:
              manifest:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: {{ $xrName }}
                  namespace: {{ $xrNamespace }}
                  labels:
                    app: whoami-xr
                    instance: {{ $xrName }}
                spec:
                  replicas: {{ $replicas }}
                  selector:
                    matchLabels:
                      app: whoami-xr
                      instance: {{ $xrName }}
                  template:
                    metadata:
                      labels:
                        app: whoami-xr
                        instance: {{ $xrName }}
                    spec:
                      containers:
                      - name: whoami
                        image: {{ $image }}
                        ports:
                        - containerPort: 80
                          name: web
                        resources:
                          requests:
                            memory: "32Mi"
                            cpu: "10m"
                          limits:
                            memory: "64Mi"
                            cpu: "100m"
                        livenessProbe:
                          httpGet:
                            path: /health
                            port: 80
                          initialDelaySeconds: 10
                        readinessProbe:
                          httpGet:
                            path: /health
                            port: 80
                          initialDelaySeconds: 5
            providerConfigRef:
              name: kubernetes-provider
            namespaceSelector:
              matchControllerRef: true
          
          ---
          # Service
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $xrName }}-service
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $xrName }}-service
              crossplane.io/external-name: {{ $xrName }}-service
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: Service
                metadata:
                  name: {{ $xrName }}
                  namespace: {{ $xrNamespace }}
                  labels:
                    app: whoami-xr
                    instance: {{ $xrName }}
                spec:
                  type: ClusterIP
                  selector:
                    app: whoami-xr
                    instance: {{ $xrName }}
                  ports:
                  - port: 80
                    targetPort: 80
                    protocol: TCP
                    name: http
            providerConfigRef:
              name: kubernetes-provider
            namespaceSelector:
              matchControllerRef: true
          
          ---
          # Ingress with dynamic domain
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $xrName }}-ingress
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $xrName }}-ingress
              crossplane.io/external-name: {{ $xrName }}-ingress
          spec:
            forProvider:
              manifest:
                apiVersion: networking.k8s.io/v1
                kind: Ingress
                metadata:
                  name: {{ $xrName }}
                  namespace: {{ $xrNamespace }}
                  labels:
                    app: whoami-xr
                    instance: {{ $xrName }}
                  annotations:
                    nginx.ingress.kubernetes.io/rewrite-target: /
                spec:
                  ingressClassName: nginx
                  rules:
                  - host: {{ $domain }}
                    http:
                      paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: {{ $xrName }}
                            port:
                              number: 80
            providerConfigRef:
              name: kubernetes-provider
            namespaceSelector:
              matchControllerRef: true
  
  # Step 3: Mark as ready when all resources are created
  - step: auto-ready
    functionRef:
      name: function-auto-ready