apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami-demo
spec:
  ingressClassName: nginx
  rules:
  # Domain is dynamically set based on environment:
  # Local: whoami.localhost
  # Production: whoami.openportal.dev (when LoadBalancer IP is 50.56.157.82)
  # Other clouds: whoami.EXTERNAL_IP.nip.io
  - host: whoami.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80