apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoami-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: whoami
  app.kubernetes.io/instance: demo
  app.kubernetes.io/managed-by: flux