# XRD: WhoAmIApp (XR Definition)
# Purpose: Define a simple demo application with automatic domain configuration
# Restaurant Analogy: The "menu item" - what customers can order
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: whoamiapps.demo.openportal.dev
  labels:
    terasky.backstage.io/generate-form: "true"
spec:
  scope: Namespaced
  group: demo.openportal.dev
  names:
    kind: WhoAmIApp
    plural: whoamiapps
  # Default to direct composition when no selector is specified
  defaultCompositionRef:
    name: whoamiapp-direct
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: Application name (becomes subdomain, e.g., myapp.openportal.dev)
                pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                minLength: 1
                maxLength: 63
              replicas:
                type: integer
                description: Number of replicas
                default: 1
                minimum: 1
                maximum: 3
              image:
                type: string
                description: Container image to deploy
                default: "traefik/whoami:v1.10.1"
            required: []
          status:
            type: object
            properties:
              domain:
                type: string
                description: The configured domain for this deployment
              ready:
                type: boolean
                description: Whether the application is ready