apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

patches:
  # Update ConfigMap for production
  - target:
      kind: ConfigMap
      name: environment-config
    patch: |-
      - op: replace
        path: /data/domain
        value: whoami.openportal.dev
      - op: replace
        path: /data/environment
        value: production
  
  # Update Ingress host for production
  - target:
      kind: Ingress
      name: whoami
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: whoami.openportal.dev
  
  # Scale up replicas for production
  - target:
      kind: Deployment
      name: whoami
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3