apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoami-demo

resources:
  - ../../

patches:
  - target:
      kind: Deployment
      name: whoami
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: whoami
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: whoami.openportal.dev
      - op: add
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: letsencrypt-prod