apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoami-demo

resources:
  - ../../

patches:
  - target:
      kind: Ingress
      name: whoami
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: whoami.127.0.0.1.nip.io