---
# Crossplane Configuration Package metadata
# This file defines how the package is built and published
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-whoami
  labels:
    provider: kubernetes
    type: application
    openportal.dev/template: "true"
spec:
  # Crossplane version compatibility
  crossplane:
    version: ">=v2.0.0"
  
  # Dependencies - provider requirements
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.14.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.19.0"